name: Play with GA

on: 
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: 'aa'
        type: choice
        options:
          - aa
          - bb
          - cc
jobs:
  play-with-ga:
    runs-on: ubuntu-latest
    steps:
      - name: GA
        run: echo "the name is ${{inputs.name}}
